-- ============================================================
-- 교재 테이블을 메인 DB(jls-counseling)에 생성 (bk_ 접두어)
-- 실행 위치: jls-counseling(메인) 프로젝트 → SQL Editor → 붙여넣고 Run
-- 빈 테이블만 생성 (기존 데이터·다른 테이블은 안 건드림). 데이터 복사는 다음 단계.
-- ※ 메인엔 이미 students·semesters 가 있어서 교재 것은 bk_ 접두어로 충돌 회피.
-- ============================================================

create table if not exists bk_bank_transactions (
  id            bigint generated by default as identity primary key,
  branch        text,
  tx_datetime   text,
  summary       text,
  counterpart   text,
  memo          text,
  withdraw      numeric default 0,
  deposit       numeric default 0,
  balance       numeric default 0,
  tx_point      text,
  tx_type       text,
  created_at    timestamptz default now(),
  unique (branch, tx_datetime, counterpart, deposit, withdraw)
);

create table if not exists bk_barcode_history (
  id            bigint generated by default as identity primary key,
  code          text not null,
  label         text not null,
  branch        text,
  created_at    timestamptz default now()
);

create table if not exists bk_books (
  barcode              text primary key,
  name                 text not null,
  subject              text,
  publisher            text,
  price                integer default 0,
  note                 text,
  created_at           timestamptz default now(),
  branch               text default 'namdongtanjls',
  vendor               text,
  level                text,
  purchase_price       integer default 0,
  level_namdongtanjls  text
);

create table if not exists bk_loan_history (
  id            bigint generated by default as identity primary key,
  barcode       text not null,
  book_name     text,
  teacher_id    text not null,
  teacher_name  text,
  loan_date     date default current_date,
  return_due    date,
  return_date   date,
  semester      text,
  status        text default '대여중',
  created_at    timestamptz default now(),
  branch        text default 'namdongtanjls'
);

create table if not exists bk_payments (
  id            bigint generated by default as identity primary key,
  branch        text,
  student_id    text,
  student_name  text,
  semester      text,
  paid_amount   numeric not null,
  paid_date     date not null,
  memo          text,
  created_at    timestamptz default now()
);

create table if not exists bk_sales_history (
  id             bigint generated by default as identity primary key,
  barcode        text not null,
  book_name      text,
  type           text not null,
  qty            integer not null default 1,
  unit_price     integer default 0,
  total          integer default 0,
  sale_date      date default current_date,
  student_id     text,
  student_name   text,
  semester       text,
  class_name     text,
  pay_status     text default '미납',
  memo           text,
  created_at     timestamptz default now(),
  branch         text default 'namdongtanjls',
  division       text,
  paid_date      date,
  purchase_price numeric,
  tax_amount     integer default 0
);

create table if not exists bk_semesters (
  id            bigint primary key,
  name          text not null,
  branch        text not null,
  created_at    timestamptz default now(),
  unique (name, branch)
);

create table if not exists bk_student_enrollments (
  id                bigint primary key,
  student_id        text not null,
  name              text,
  semester          text,
  grade             text,
  class_name        text,
  homeroom_teacher  text,
  contact           text,
  branch            text,
  division          text,
  is_active         boolean default true,
  created_at        timestamp default now(),
  updated_at        timestamp default now()
);

create table if not exists bk_students (
  student_id    text not null,
  name          text not null,
  contact       text,
  grade         text,
  class_name    text,
  semester      text not null,
  note          text,
  created_at    timestamptz default now(),
  branch        text default 'namdongtanjls',
  division      text default 'CHESS',
  status        text,
  updated_at    timestamp,
  school        text,
  primary key (student_id, semester),
  unique (student_id, branch)
);

create table if not exists bk_students_history (
  snapshot_at   timestamptz not null default now(),
  student_id    text,
  name          text,
  contact       text,
  grade         text,
  class_name    text,
  semester      text,
  note          text,
  created_at    timestamptz,
  branch        text,
  division      text,
  status        text,
  updated_at    timestamptz,
  school        text
);

create table if not exists bk_teachers (
  teacher_id    text primary key,
  name          text not null,
  subject       text,
  contact       text,
  created_at    timestamptz default now(),
  branch        text default 'namdongtanjls'
);

create table if not exists bk_transfers (
  id             bigint generated by default as identity primary key,
  from_branch    text,
  to_branch      text,
  barcode        text,
  book_name      text,
  qty            integer default 1,
  purchase_price numeric,
  handler        text,
  status         text,
  created_at     timestamptz default now(),
  confirmed_at   timestamptz
);

create table if not exists bk_vendors (
  id            integer generated by default as identity primary key,
  name          text not null,
  vat_yn        boolean default false,
  created_at    timestamptz default now(),
  unique (name)
);

-- 앱(익명 키)이 접근 가능하도록 — 메인의 기존 테이블과 동일하게 RLS off + 권한 부여
alter table bk_bank_transactions   disable row level security;
alter table bk_barcode_history     disable row level security;
alter table bk_books               disable row level security;
alter table bk_loan_history        disable row level security;
alter table bk_payments            disable row level security;
alter table bk_sales_history       disable row level security;
alter table bk_semesters           disable row level security;
alter table bk_student_enrollments disable row level security;
alter table bk_students            disable row level security;
alter table bk_students_history    disable row level security;
alter table bk_teachers            disable row level security;
alter table bk_transfers           disable row level security;
alter table bk_vendors             disable row level security;

grant all on bk_bank_transactions, bk_barcode_history, bk_books, bk_loan_history,
             bk_payments, bk_sales_history, bk_semesters, bk_student_enrollments,
             bk_students, bk_students_history, bk_teachers, bk_transfers, bk_vendors
  to anon, authenticated;
